IMAGE_STORE_DIR_CONFIG:
  temporary: /tmp
  realstate: /realstate
  community: /community
  website: /website

IMAGE_STORE_CONFIG:
  host: http://palza-market-image-store.s3-website.ap-northeast-2.amazonaws.com

DATABASE_CONFIG:
  protocol: mongodb
  endpoint: palza-market-db.cluster-cxz5zqdhkz22.ap-northeast-2.docdb.amazonaws.com:27017
  username: master
  password: 12345678
  database: palza-market
  config:
    replicaSet: rs0
    readPreference: secondaryPreferred
    retryWrites: false