CORS:
  origins: 
    - http://palza-market-main.s3-website.ap-northeast-2.amazonaws.com
    - http://localhost:3000

SETTINGS: 
  title: Palza Market
  description: Palza Market
  fax_no: 02-000-0000
  kakao_key: 2c2744b65e19d51683e55859e2aa4491
  naver_key: 2c2744b65e19d51683e55859e2aa4491
  google_key: 2c2744b65e19d51683e55859e2aa4491
  # sms..
  gabia_sms_id: escada98969896
  gabia_sms_key: 75d5e00645c569a59ac63630c7588fec
  gabia_sms_callback_number: 01043730793
  # business info..
  nsdi_key: 1f5c58af868b1df99706da
  # crawling..
  odcloud_key: MgY51pDPRtCjEZlQz%2B2ZCiZvTnxEPoABjRFnRQXMcQtyaC3hwLF8P51nid7ghxIKhXxu7SAhqAfM7Snxmlj8hA%3D%3D

SECRET: 
  key: 25d8cd8be9894e7b479e69e3fd69c8e8ea61b1f99e3660888c3b4389a13777b1
  algo: HS256
  expires_in: 60 # in minutes..

IMAGE_STORE_DIR_CONFIG:
  temporary: temporary
  realstate: realstate
  home_page: home_page
  notice: notice
  others: others

IMAGE_STORE_CONFIG:
  host: http://palza-market-image-store-dev.s3-website.ap-northeast-2.amazonaws.com
  bucket: palza-market-image-store
  aws_access_key_id: AKIAW7OMABNVE2ZGIP6J
  aws_secret_access_key: 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
  aws_region: ap-northeast-2

DATABASE_CONFIG:
  protocol: mongodb
  host: palza-market-db.cluster-cxz5zqdhkz22.ap-northeast-2.docdb.amazonaws.com
  port: 27017
  username: master
  password: 12345678
  database: palza-market