IMAGE_STORE_DIR_CONFIG:
  temporary: /tmp
  realstate: /realstate
  community: /community
  website: /website

IMAGE_STORE_CONFIG:
  host: http://palza-market-image-store.s3-website.ap-northeast-2.amazonaws.com

# mongodb://master:<insertYourPassword>@palza-market-db.cluster-cxz5zqdhkz22.ap-northeast-2.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
DATABASE_CONFIG:
  protocol: mongodb
  host: palza-market-db.cluster-cxz5zqdhkz22.ap-northeast-2.docdb.amazonaws.com
  port: 27017
  username: master
  password: 12345678
  config:
    ssl: true
    ssl_ca_certs: rds-combined-ca-bundle.pem
    replicaSet: rs0
    readPreference: secondaryPreferred
    retryWrites: false